# Generated by Django 2.1.3 on 2018-11-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_galery', '0002_auto_20181121_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='producer',
        ),
    ]
